name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: npm
          # cache-dependency-path: 'pnpm-lock.yaml'
      # - run: yarn install --frozen-lockfile


      - name: Build-1
        # run : npm run build
        run: pnpm i 
      - name: Build-2
        run: pnpm run dev
      - name: Build-3
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          # cname: example.com # if wanna deploy to custom domain
