name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build-0
        run: npm install -g pnpm
      - name: Build-1
        # run : npm run build
        # run: pnpm i 
        run: pnpm install --no-frozen-lockfile
      - name: Build-3
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          # cname: example.com # if wanna deploy to custom domain
